### ISSUE TITLE
how to set username and password ?

### ISSUE THREAD

**Issue by Xsmael** [badlee/kannel.js#4]
I've been using kannel from kannel.org and wanted to try the nodejs version

but from your documentation i dont see where to set the username and password to connect through SMPP protocol to the SMS server

**Comment by badlee** [comment]
Hi sorry for the late.
Kanel.js allow write an smsbox in js,all configurations (Username, Password, Ton, etc...) is in kannel.conf.

If you looking for an SMPP gateway go to  https://github.com/badlee/scriptbox
